name: line_bot_sdk_dart
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  crypto: ^2.1.5
  http: ^0.12.2
  json_annotation: ^3.0.0

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^3.2.0
  pedantic: ^1.9.0
  test: ^1.14.4
