name: linebot
description: SDK of the LINE Messaging API for Dart.
version: 0.0.1
repository: https://github.com/cychiang/line-bot-sdk-dart
issue_tracker: https://github.com/cychiang/line-bot-sdk-dart/issues
homepage: https://github.com/cychiang/line-bot-sdk-dart

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  crypto: ^2.1.5
  http: ^0.12.2
  json_annotation: ^3.0.0

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^3.2.0
  pedantic: ^1.9.0
  test: ^1.14.4
